Fuseaux horaires
betagouv/preuve-covoiturage pull request #1099
Opened 2020-11-05 14:48 UTC by jonathanfallon

#706. Prise en charge des fuseaux horaires sur les stats et l'export

2020-11-10 08:27 UTC, nmrgt requested changes

2020-11-10 08:27 UTC, nmrgt commented on api/services/trip/src/actions/BuildExportAction.ts
>    journey_end_date: string;
Pourquoi ajouter start_datetime ici ?

2020-11-10 08:27 UTC, nmrgt commented on api/services/trip/src/actions/ExportAction.ts
> +        territory_authorized_operator_id: get(context, 'call.user.authorizedOperators', []) || [],
le || est inutile puisque la méthode get de lodash inclut un défaut. non ?

2020-11-10 08:27 UTC, nmrgt commented on api/services/trip/src/actions/ListAction.ts
> +    const authorizedOperators = get(context, 'call.user.authorizedOperators', null) || null;
idem

2020-11-10 08:27 UTC, nmrgt commented on api/services/trip/src/interfaces/ExportTripInterface.ts
> +  journey_start_datetime: Date | string;
pourquoi ce | string ?

2020-11-10 08:27 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +          ON true
Attention au perf sur un lateral

2020-11-10 08:27 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      : [];
Je ne comprends pas. Peux-tu préciser l'utilité de ce code ?

2020-11-10 08:27 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      campaigns_id: [...new Set(map(data.campaigns_id || [], 'policy_id'))].sort(),
je pense que le sort est inutile

2020-11-10 08:27 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      data: orderBy(final_data, 'start_datetime', 'desc'),
pourquoi faire un order by ici, les données sont déjà triés par pg, non ?

2020-11-10 08:49 UTC, jonathanfallon commented on api/services/trip/src/actions/BuildExportAction.ts
>    journey_end_date: string;
Parce qu'on converti son format dans le bon fuseau horaire et qu'il doit être normalisé par la fonction `normalize` dont l'interface de sortie est `FlattenTripInterface`

2020-11-10 08:51 UTC, jonathanfallon commented on api/services/trip/src/actions/ExportAction.ts
> +        territory_authorized_operator_id: get(context, 'call.user.authorizedOperators', []) || [],
Non car on a des cas où PG nous renvoie `null` et non `[]` comme valeur donc la valeur par défaut de `get()` n'est pas utilisée et ça provoque une erreur car le type attendu est un `[]`

2020-11-10 08:51 UTC, jonathanfallon commented on api/services/trip/src/actions/ListAction.ts
> +    const authorizedOperators = get(context, 'call.user.authorizedOperators', null) || null;
idem

2020-11-10 08:52 UTC, jonathanfallon commented on api/services/trip/src/interfaces/ExportTripInterface.ts
> +  journey_start_datetime: Date | string;
les _datetime_ formatés dans le bon fuseau sont des `string` et non des `Date` (converties en `ISOString`, ce qui n'est pas le format attendu.

2020-11-10 08:53 UTC, jonathanfallon commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +          ON true
J'ai pas trouvé d'autre solution ici et nous sommes sur de l'export (async) des stats (mises en cache) ou du trip.list : 10 résultats par page donc ça devrait aller.

2020-11-10 08:59 UTC, nmrgt commented on api/services/trip/src/actions/BuildExportAction.ts
>    journey_end_date: string;
Oui mais FlattenTripInterface hérite de ExportTripInterface qui a déjà ce champ.

2020-11-10 09:02 UTC, nmrgt commented on api/services/trip/src/actions/ExportAction.ts
> +        territory_authorized_operator_id: get(context, 'call.user.authorizedOperators', []) || [],
Sauf qu'il n'y a pas pg dans l'équation ici, on prend un champ qui vient du context. S'il n'est pas défini, il est undefined et get() prend la valeur par défaut. Il me semble que si on a un user.authorizedOperators null quelque part c'est qu'il faut caster dans le proxy (là on met en place cette valeur), plutôt qu'ici.

2020-11-10 09:02 UTC, nmrgt commented on api/services/trip/src/actions/ListAction.ts
> +    const authorizedOperators = get(context, 'call.user.authorizedOperators', null) || null;
idem ;)

2020-11-10 09:06 UTC, nmrgt commented on api/services/trip/src/interfaces/ExportTripInterface.ts
> +  journey_start_datetime: Date | string;
Non, je ne pense pas. Ici, il s'agit d'un type utilisé en sortie du repository (qui donne une date donc) et dans BuildExportAction. Si tu veux permettre que le FlattenTripInterface utilise du texte (pour la sortie de formateur CSV) il faut surcharger cette interface et non celle ci.

2020-11-10 09:16 UTC, jonathanfallon commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      : [];
J'ai simplifié, le casting en `::text` de la date fait mieux le taff

2020-11-10 09:16 UTC, jonathanfallon commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      campaigns_id: [...new Set(map(data.campaigns_id || [], 'policy_id'))].sort(),
`map()` ne conserve pas l'ordre du tableau et ça ne sortait pas comme il faut, d'où le `sort()`

2020-11-10 09:17 UTC, jonathanfallon commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      data: orderBy(final_data, 'start_datetime', 'desc'),
`final_data = result.rows.map` mm problème que plus haut... merci Javascript !

2020-11-10 09:20 UTC, jonathanfallon commented on api/services/trip/src/actions/BuildExportAction.ts
>    journey_end_date: string;
Tant que l'on garde le type `string` dans l'un ou l'autre, ça fait le taff.

2020-11-10 09:26 UTC, jonathanfallon commented on api/services/trip/src/actions/ExportAction.ts
> +        territory_authorized_operator_id: get(context, 'call.user.authorizedOperators', []) || [],
En l'occurence, on a eu le soucis et je préfère garder une sécu qui marche même si on trouve le problème à la racine.

2020-11-10 09:26 UTC, jonathanfallon commented on api/services/trip/src/actions/ListAction.ts
> +    const authorizedOperators = get(context, 'call.user.authorizedOperators', null) || null;
idem bis repetita :D

2020-11-10 09:28 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      campaigns_id: [...new Set(map(data.campaigns_id || [], 'policy_id'))].sort(),
```suggestion
      campaigns_id: [...new Set((data.campaigns_id || []).map(c => c.policy_id))],
```
?

2020-11-10 10:09 UTC, nmrgt requested changes

2020-11-10 10:09 UTC, nmrgt commented on api/services/trip/src/actions/BuildExportAction.ts
> +interface FlattenTripInterface<JourneyDateTimeType> extends ExportTripInterface<JourneyDateTimeType> {
interface FlattenTripInterface extends ExportTripInterface<JourneyDateTimeType>, non ?

2020-11-10 10:09 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +        day::text,
Si tu caste en texte, tu vas avoir un soucis sur le type de sortie du repository (qui attend une date).

2020-11-10 10:09 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      data: orderBy(final_data, 'start_datetime', 'desc'),
A priori, la fonction map native sur un tableau conserver l'ordre, cf plus haut (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/map)

2020-11-12 10:30 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      campaigns_id: [...new Set(map(data.campaigns_id || [], 'policy_id'))].sort(),
```js
let finalArray = new Array(initialArray.length);
for(let (toto, i) in initialArray) {
 // do something
 finalArray[i] = toto;
}
```

2020-11-12 10:44 UTC, nmrgt commented
- virer le filtre horaire (pour virer le lateral) ;
- éventuellement, régler le problème de l'order by ;
- investiguer le casting dans le driver pg pour supporter les TZ ;

2020-11-12 20:59 UTC, jonathanfallon commented on api/services/trip/src/actions/BuildExportAction.ts
> +interface FlattenTripInterface<JourneyDateTimeType> extends ExportTripInterface<JourneyDateTimeType> {
Le type est passé à `FlattenTripInterface` quand la fonction `normalize` l'utilise. On pourrait simplifier en :
`FlattenTripInterface extends ExportTripInterface<string>`

2020-11-19 13:15 UTC, merged