Simulation de campagne V1
betagouv/preuve-covoiturage pull request #1114
Opened 2020-11-23 18:35 UTC by gillesboisson

Intégration d'un panneau de simulation de campagne dans les écrans de création de campagne de prévisualisation de brouillon de campagne.

Des correctifs et adaptation dans l'API :
- passage de la limite à 3 mois (4 mois théorique car intervalle de simulation s'aligne au 1er du mois précédent)
- correctif d'un bug de correction de campagne (bug campagne sans template)
- application d'un correctif sur l'API de simulation (mauvaise utilisation du moteur d'incitation)

2020-11-24 08:07 UTC, nmrgt requested changes

2020-11-24 08:07 UTC, nmrgt commented on shared/common/interfaces/CampaignInterface.ts
> +  };
Pourquoi modifier ça ici ?

2020-11-24 09:53 UTC, jonathanfallon requested changes

2020-11-24 09:53 UTC, jonathanfallon commented on package.json
>      "eslint-plugin-prettier": "^3.1.4",
Possible de mettre à jour tous les paquets eslint ?

```
@typescript-eslint/parser@4.8.2
@typescript-eslint/eslint-plugin@4.8.2
eslint@7.14.0
```

2020-11-24 09:53 UTC, jonathanfallon commented on api/providers/pdfcert/src/assets/marianne.ts
> +      // eslint-disable-next-line max-len
il y a déjà un `eslint-disable` en haut donc ce n'est plus utile. ça doit venir d'un merge.
```suggestion
```

2020-11-24 09:53 UTC, jonathanfallon commented on api/providers/pdfcert/src/assets/marianne.ts
> +      // eslint-disable-next-line max-len
mm chose
```suggestion
```

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/package.json
> +    "typescript": "~4.0.3",
Dernière version : ça vaut le coup de faire la mise à jour ?
`typescript@4.1.2`

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
> +  // }
Cleanup ?

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.html
> +  <h4>Simulation de votre campagne sur une durée {{ timeState.nbMonth }} mois</h4>
```suggestion
  <h4>Simulation de votre campagne sur une durée de {{ timeState.nbMonth }}&nbsp;mois</h4>
```

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.html
> +  <p>Cette estimation cses base sur les trajets réalisés sur votre du {{ timeState.startDateString }} au {{ timeState.endDateString }} </p>
```suggestion
  <p>Cette estimation se base sur les trajets réalisés du {{ timeState.startDateString }} au {{ timeState.endDateString }}.</p>
```

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.html
> +    <p>{{ state.trip_subsidized }} </p>
```suggestion
    <p>{{ state.trip_subsidized }}</p>
```

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.html
> +    <p>{{ state.amount }} €/pts</p>
```suggestion
    <p>{{ state.amount }}&nbsp;€/pts</p>
```

2020-11-24 09:53 UTC, jonathanfallon commented on api/services/policy/src/actions/SimulateOnPastAction.ts
> +    ['validate.date', ['campaign', new Date(new Date().getTime() - 1000 * 60 * 60 * 24 * 31 * 4), new Date()]],
Un petit `date-fns` ici ? Ce serait beaucoup plus lisible.

```typescript
import {add} from 'date-fns';
// ...
add(new Date(), {months: 4});
```

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/src/app/core/entities/campaign/api-format/campaign.formater.ts
> +      // parent_id: parent_id || 0,
```suggestion
```

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.html
```suggestion
```

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.html
> +  <p>Cette estimation cses base sur les trajets réalisés sur votre du {{ timeState.startDateString }} au {{ timeState.endDateString }} </p>
```suggestion
  <p>Cette estimation se base sur les trajets réalisés du {{ timeState.startDateString }} au {{ timeState.endDateString }}</p>
```

2020-11-24 09:53 UTC, jonathanfallon commented on dashboard/src/app/modules/campaign/components/campaign-simulation-pane/campaign-simulation-pane.component.html
>  </div>
Il n'y a pas un soucis d'indentation ici ?
```suggestion
</div> 
 
```

2020-11-24 09:53 UTC, jonathanfallon commented on shared/common/interfaces/CampaignInterface.ts
> +  };
On pourrait pas utiliser `CampaignStats` qui est importé en haut (en commentaire) ?

2020-11-25 14:13 UTC, jonathanfallon approved these changes

2020-11-25 14:44 UTC, merged