[fix] Attestations
betagouv/preuve-covoiturage pull request #1320
Opened 2021-04-14 08:51 UTC by jonathanfallon

- ajout de paramètres sur la méthode findUUID() qui cherche les identités dans `carpool.identities`
- ajout de messages d'erreur dans l'UI pour 401 et 403

2021-04-15 07:45 UTC, nmrgt requested changes

2021-04-15 07:45 UTC, nmrgt commented on api/services/carpool/src/providers/IdentityRepositoryProvider.ts
>            AND travel_pass_name = $5::varchar AND travel_pass_user_id = $6::varchar
Je pense qu'il faut ajouter deux index sur la table en question : 
- l'un sur le created_at
- l'autre sur [phone_trunc,travel_pass_name,travel_pass_user_id]

2021-04-15 07:45 UTC, nmrgt commented on api/services/certificate/src/actions/CreateCertificateAction.ts
> +    const operator = await this.findOperator(operator_id, context);
quel est l'intérêt de passer le contexte ?

2021-04-15 07:45 UTC, nmrgt commented on api/services/certificate/src/actions/CreateCertificateAction.ts
>    private castParams(params: ParamsInterface): ParamsInterface & { start_at: Date; end_at: Date } {
Est-ce que cette fonction ne peut pas être remplacée par le middleware date ?

2021-04-15 07:45 UTC, nmrgt commented on dashboard/src/app/modules/certificate/certificate-layout/certificate-layout.component.html
> +            href="https://doc.covoiturage.beta.gouv.fr/employeurs-et-employes-developper-du-forfait-mobilite-durables/telecharger-les-attestations-operateurs"
C'est pas gênant mais ce serait plus propre de mettre ça dans une variable (comme les autres urls).

2021-04-15 07:45 UTC, nmrgt commented on dashboard/src/manual-503.html
> +                      href="https://doc.covoiturage.beta.gouv.fr/ressources/mentions-legales"
Pareil ici.

2021-04-15 07:45 UTC, nmrgt commented on dashboard/src/manual-503.html
> +                      href="https://doc.covoiturage.beta.gouv.fr"
Pareil ici.

2021-04-15 07:45 UTC, nmrgt commented on api/services/carpool/src/providers/IdentityRepositoryProvider.ts
> +    const opts: findUuidOptions = { create: false, interval: 0, ...options };
J'ai probablement raté quelque chose mais je ne vois pas où ce nouveau paramètre est utilisé dans la PR :)

2021-04-15 10:29 UTC, jonathanfallon commented on api/services/certificate/src/actions/CreateCertificateAction.ts
> +    const operator = await this.findOperator(operator_id, context);
pour avoir la permission de l'utilisateur quand on appelle le kernel dans l'action.
`findOperator` est une méthode privée de cette action.

2021-04-15 10:30 UTC, jonathanfallon commented on api/services/carpool/src/providers/IdentityRepositoryProvider.ts
> +    const opts: findUuidOptions = { create: false, interval: 0, ...options };
dans la méthode `create` au dessus qui passe un `{ create: true, interval: 30 }`

2021-04-15 11:13 UTC, jonathanfallon commented
- [ ] index sur les tables
- [ ] create -> generate
- [ ] middleware dates -> faire une refacto

2021-04-15 16:07 UTC, jonathanfallon commented on dashboard/src/app/modules/certificate/certificate-layout/certificate-layout.component.html
> +            href="https://doc.covoiturage.beta.gouv.fr/employeurs-et-employes-developper-du-forfait-mobilite-durables/telecharger-les-attestations-operateurs"
en fait c'est une page statique cette 503 donc elle n'a pas accès aux constantes de l'app comme un composant normal.

2021-04-15 16:27 UTC, jonathanfallon commented on api/services/certificate/src/actions/CreateCertificateAction.ts
>    private castParams(params: ParamsInterface): ParamsInterface & { start_at: Date; end_at: Date } {
En regardant de près, le middleware ne supporte pas ce cas d'usage et ne permet pas l'utilisation du ConfigProvider donc je vais laisser comme ça.

2021-04-15 16:40 UTC, jonathanfallon commented on api/services/carpool/src/providers/IdentityRepositoryProvider.ts
>            AND travel_pass_name = $5::varchar AND travel_pass_user_id = $6::varchar
done

2021-04-16 09:36 UTC, nmrgt approved these changes

2021-04-16 09:36 UTC, merged