Feat/1426
betagouv/preuve-covoiturage pull request #1457
Opened 2021-08-09 14:30 UTC by P3rceval

2021-08-30 12:10 UTC, nmrgt requested changes

2021-08-30 12:10 UTC, nmrgt commented on api/services/trip/src/actions/excel/ExcelWorkbookHandler.ts
> +      ) + '.xlsx';
le linter ne veut pas te forcer à utiliser un template string ?

2021-08-30 12:10 UTC, nmrgt commented on api/services/trip/src/actions/excel/GetCampaignAndCallBuildExcel.ts
> +    return await this.buildExcelFileForCampaign.call(campaign_id, start_date, end_date, campaign.name);
je pense qu'il faut éviter de faire de la composition de même niveau à plusieurs endroits, non ?

2021-08-30 13:49 UTC, P3rceval commented on api/proxy/src/HttpTransport.ts
> +  }
C'était une de mes interrogations. L'action est exposée via `/rpc` de base c'est ça ? 
(J'ai pas pu utiliser le système de Commande finalement, parce le DI n'a pas l'air de fonctionner)

2021-08-30 13:49 UTC, P3rceval commented on api/proxy/src/HttpTransport.ts
> +    );
Non, c'est bien un duplicate :S :S. (Surement un mauvais copier/coller...) Je l'enlève

2021-08-30 13:49 UTC, P3rceval commented on api/services/trip/src/actions/BuildExcelExportAction.spec.ts
> +  sinon.assert.calledOnceWithExactly(getCampaignAndCallBuildExcelStub, CAMPAIGN_ID, null, null);
`calledOnceWithExactly` renvoie `void` :thinking:

2021-08-30 13:49 UTC, P3rceval commented on api/services/trip/src/actions/BuildExcelExportAction.ts
> +    this.castOrSetDefaultDates(params);
Yes j'suis d'accord

2021-08-30 13:49 UTC, P3rceval commented on api/services/trip/src/actions/BuildExcelExportAction.ts
> +        .then((filepath) => this.s3StorageProvider.upload(BucketName.Export, filepath))
J'avais pas fait attention pendant notre call mais y'a bien un catch en dessous :thinking: . C'est good du coup non ?

2021-08-30 13:49 UTC, P3rceval commented on api/services/trip/src/actions/BuildExcelExportAction.ts
> +  }
Effectivement, c'est parce qu'à la base j'étais partie sur au moins une campagne **ou** un territoire. Finalement, je me suis limité aux campagnes. Donc j'peux remove ce code

2021-08-30 13:49 UTC, P3rceval commented on api/services/trip/src/actions/excel/ExcelWorkbookHandler.ts
> +      ) + '.xlsx';
Non, il faut rajouter  ` 'prefer-template': 'error'`,  à la conf d'`eslintrc.js`  (je l'ajoute)

2021-08-30 13:49 UTC, P3rceval commented on api/services/trip/src/actions/excel/ExcelWorkbookHandler.ts
> +      .replace(/[\u0300-\u036f]/g, '');
Pour avoir fait une semaine d'appels de fonds, la donnée clés, c'est vraiment le mois xD. J'ai envie de dire, on fera un refacto si y'a d'autres usages ? :)

2021-08-30 13:49 UTC, P3rceval commented on api/services/trip/src/actions/excel/GetCampaignAndCallBuildExcel.ts
> +    return await this.buildExcelFileForCampaign.call(campaign_id, start_date, end_date, campaign.name);
Suite à notre call, j'ai une vague idée de ce qu'il faut faire. 
J'pense que je peux tenter un refacto post merge ?

2021-08-30 14:21 UTC, nmrgt commented on api/proxy/src/HttpTransport.ts
> +  }
Yes. Pour les commandes, tu peux faire un yarn ilos call mon_action -c '{}' -p '{}' où -c = context et -p = params

2021-08-30 14:23 UTC, nmrgt commented on api/services/trip/src/actions/BuildExcelExportAction.spec.ts
> +  sinon.assert.calledOnceWithExactly(getCampaignAndCallBuildExcelStub, CAMPAIGN_ID, null, null);
ah oui pardon c'est 
```
  t.true(t.context.stub.sendMail.calledOnce);
  const { text, html, subject, to } = t.context.stub.sendMail.getCall(0).args[0]
```

2021-08-30 14:31 UTC, nmrgt commented on api/services/trip/src/actions/excel/ExcelWorkbookHandler.ts
> +      .replace(/[\u0300-\u036f]/g, '');
oui dans tous les cas on pourra faire une refacto :)
je pensais simplement à un getMonthString(currentDate = new Date()) histoire de pouvoir "rejouer" l'export parce que sinon tu es coincé avec ton export initial (ex: tu veux refaire l'export du mois de mars)

2021-08-31 07:26 UTC, P3rceval commented on api/services/trip/src/actions/excel/ExcelWorkbookHandler.ts
> +      .replace(/[\u0300-\u036f]/g, '');
J'ai ajouté un uuid tronqué à la fin. Y'a un risque infime pour que 2 fichiers s'appellent pareil mais ça devrait pas arriver souvent...

2021-08-31 07:44 UTC, P3rceval commented on api/services/trip/src/actions/BuildExcelExportAction.spec.ts
> +  sinon.assert.calledOnceWithExactly(getCampaignAndCallBuildExcelStub, CAMPAIGN_ID, null, null);
Je mets un check sur l'argument histoire d'éviter le `t.pass()` mais en soit c'est déjà fait via les tests sinon.

2021-08-31 07:45 UTC, P3rceval commented on api/services/trip/src/actions/BuildExcelExportAction.ts
> +        .then((filepath) => this.s3StorageProvider.upload(BucketName.Export, filepath))
Par contre je rajoute le log de l'exception pour avoir l'origine ...

2021-08-31 07:55 UTC, nmrgt commented on api/services/trip/src/actions/excel/ExcelWorkbookHandler.ts
> +      .replace(/[\u0300-\u036f]/g, '');
ok je pensais pas forcément à un conflit mais comme tu fais un new Date ligne 31 tu peux pas refaire l'export du mois de mars au mois de septembre par exemple, si ?

2021-08-31 09:40 UTC, nmrgt approved these changes

2021-08-31 09:41 UTC, merged

2021-09-02 08:52 UTC, P3rceval commented on api/services/trip/src/actions/excel/ExcelWorkbookHandler.ts
> +      .replace(/[\u0300-\u036f]/g, '');
Oaui effectivement, j'ai pris le cas nominal qui est la génération du excel le 6 du mois, pour le mois précédent, mais c'est pas exceptionnel si on refait des générations à posteriori.