Update policy engine
betagouv/preuve-covoiturage pull request #1475
Opened 2021-09-07 08:04 UTC by nmrgt

- wayback machine
- #1333

2021-09-10 07:36 UTC, nmrgt commented on api/services/policy/src/engine/rules/filters/InseeFilter.ts
> +// This rule is deprecated, please migrate to territory filter instead
Tout à fait, c'est dans la TODO de la PR (cf description).

Concernant la dépréciation de la règle territory filter, je pense qu'une fois que le chantier territoire sera fini, on fera une nouvelle règle avec [type_de_code, code] pour couvrir l'ensemble des cas (comme peut le gérer actuellement le territory filter).

2021-09-10 07:37 UTC, nmrgt commented on api/services/policy/src/engine/rules/native/IdfmRegular.spec.ts
>  test('case 1', async (t) => {
Tout à fait, c'est dans la TODO de la PR (cf description) :)

Par contre ce fichier de test est un legacy sur une règle native qui n'est plus utilisée aujourd'hui.

2021-09-15 15:49 UTC, jonathanfallon approved these changes

2021-09-16 13:54 UTC, jonathanfallon commented
Front à terminer pour enlever les règles qui sont dépréciées.

2021-11-02 13:27 UTC, P3rceval requested changes

2021-11-02 13:27 UTC, P3rceval commented on api/services/policy/src/providers/TripRepositoryProvider.ts
> +      values: ['2021-05-20T00:00:00Z', '2021-05-21T00:00:00Z', descendants, policy.policy_id],
Y'a pas un petite oubli ici ?

2021-11-02 13:27 UTC, P3rceval commented on api/services/policy/src/providers/TripRepositoryProvider.ts
> +    await this.connection.getClient().query(`CREATE INDEX ON ${tableName} (start_territory_id)`);
Ça doit pas faire gagner beaucoup de temps, mais j'aurai fait passer un max de requêtes en une seule connexion

2021-11-02 13:29 UTC, P3rceval commented
Est-ce que y'a des choses à terminer coté front ?

2021-11-02 13:38 UTC, nmrgt commented on api/services/policy/src/engine/PolicyEngine.spec.ts
>  test('should work with amount restriction', async (t) => {
à priori si puisqu'il a eu 40, et au lieu d'avoir 4km x 20 cts il a que 10. Par contre le premier calcul tombe juste mais pour une mauvaise raison (ancien jeu de données répartition conducteur) : 
*(4000 / 1000) * 20) / 2** = 2000/1000 * 20

Non ?

2021-11-03 14:09 UTC, P3rceval approved these changes

2021-11-03 14:47 UTC, merged