feat/opendata_excluded_territories
betagouv/preuve-covoiturage pull request #1483
Opened 2021-09-09 07:36 UTC by P3rceval

https://github.com/betagouv/preuve-covoiturage/issues/233

2021-09-09 07:37 UTC, P3rceval commented on api/services/trip/src/actions/BuildExportAction.ts
> +        ...params.query?.date,
cf comment ici => https://github.com/betagouv/preuve-covoiturage/pull/1449#discussion_r701237241

2021-09-14 07:01 UTC, nmrgt requested changes

2021-09-14 07:01 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +import { QueryConfig } from 'pg/index';
Attention, tu crées une dépendance à pg qui n'est pas dans le package.json

2021-09-14 07:01 UTC, nmrgt commented on api/services/trip/src/actions/BuildExportAction.ts
> +        queryParam.excluded_start_territory_id = excluded_start_territories.map((t) => t.start_territory_id);
même remarque que ci dessous : pourquoi seulement le start ? :)

2021-09-17 08:46 UTC, P3rceval commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +      HAVING COUNT (start_territory_id) < 6
C'était spécifié comme ça par Margot, j'ai posé la même question [ici](https://github.com/betagouv/preuve-covoiturage/issues/233) ... Je vais le faire par précaution

2021-09-22 09:30 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +import { QueryConfig } from 'pg/index';
pas d'effet de bord particulier, juste la dépendance est pas dans le paquet du code en question

2021-09-22 09:33 UTC, nmrgt approved these changes

2021-09-22 11:41 UTC, merged