Fix/opendata upload
betagouv/preuve-covoiturage pull request #1547
Opened 2021-11-03 16:53 UTC by P3rceval

2021-11-04 08:23 UTC, nmrgt requested changes

2021-11-04 08:23 UTC, nmrgt commented on api/services/trip/package-lock.json
>    "lockfileVersion": 1,
pourquoi il y a un fichier package-lock ? on utilise pas yarn ?

2021-11-04 08:23 UTC, nmrgt commented on api/services/trip/src/actions/BuildExportAction.ts
> +    return filename;
Est-ce que dans le cas d'un export non open data filename ne doit pas être égal à zipname ?

2021-11-04 08:23 UTC, nmrgt commented on api/services/trip/src/actions/BuildExportAction.ts
> +      this.removeFromFs(filepath);
est-ce qu'il ne faudrait pas dans tous les cas supprimer le fichier après son utilisation ?

2021-11-04 08:23 UTC, nmrgt commented on api/services/trip/src/actions/PublishOpenDataAction.ts
> +      const description: string = await this.buildResourceDescription.call(context.call.metadata);
Pourquoi ces données de requête sont dans les méta données ? A priori c'est bien un paramètre de la fonction et non un contexte d'exécution, si ?

2021-11-04 08:23 UTC, nmrgt commented on api/services/trip/src/actions/PublishOpenDataAction.ts
> +      await this.datagouv.updateResource(datasetSlug, uplaodResource);
```suggestion
      const uploadResource: UploadedResource = await this.datagouv.uploadResources(datasetSlug, filepath);
      await this.datagouv.updateResource(datasetSlug, { ...uploadResource, description);
```

2021-11-08 08:26 UTC, P3rceval commented on api/services/trip/package-lock.json
>    "lockfileVersion": 1,
En effet, je le supprime !

2021-11-08 10:35 UTC, P3rceval commented on api/services/trip/src/actions/PublishOpenDataAction.ts
> +      const description: string = await this.buildResourceDescription.call(context.call.metadata);
Je l'ai passé en contexte car c'est des paramètres générés par l'action BuildExport qui appelle Opendata ... 
Si tu penses que c'est mieux en param, dis moi, je fais la modification !

2021-11-08 12:59 UTC, nmrgt commented on api/services/trip/src/actions/BuildExportAction.ts
> +    return filename;
bah effectivement dans le cas d'usage c'est pas utile d'avoir le bon nom de fichier à la fin mais du coup on a une action qui renvoie le bon nom dans le cas d'un export et le mauvais dans le cas d'un open data, c'est ça ?

2021-11-08 13:02 UTC, nmrgt commented on api/services/trip/src/actions/PublishOpenDataAction.ts
> +      const description: string = await this.buildResourceDescription.call(context.call.metadata);
bah grosso modo si c'est le contexte d'execution (qui appelle ? par quel biais ?) ou des instructions pour le planificateur (comment executer) c'est dans le contexte, sinon c'est un paramètre. Je pense que c'est mieux de le mettre en param dans le cas présent

2021-11-08 13:13 UTC, P3rceval commented on api/services/trip/src/actions/BuildExportAction.ts
> +    return filename;
Ça dépend ce que t'entends par bon nom ou pas :P. Dans le cas d'un export non-opendata le fichier csv est quand même généré. 
Mais je vais faire la modification, ça sera plus logique je pense :)

2021-11-08 13:13 UTC, P3rceval commented on api/services/trip/src/actions/PublishOpenDataAction.ts
> +      const description: string = await this.buildResourceDescription.call(context.call.metadata);
Effectivement c'était pas ma compréhension du contexte ! Je fais la modif

2021-11-08 14:53 UTC, nmrgt approved these changes

2021-11-08 14:53 UTC, merged