deps update
betagouv/preuve-covoiturage pull request #1619
Opened 2021-12-21 17:23 UTC by jonathanfallon

Pour fixer des alerts dependabots. Mise à jour de dépendances sur l'API et les tests.

Suppression d'un `yarn.lock` dans `api/db` qui n'est pas utile car Lerna utile `api/yarn.lock` pour le tracking.

2021-12-22 15:25 UTC, P3rceval approved these changes

2021-12-22 15:26 UTC, P3rceval requested changes
Des unit tests à fix :)

2022-01-07 15:17 UTC, nmrgt approved these changes

2022-01-07 15:25 UTC, P3rceval commented
Est-ce qu'on ajouterai pas la version de NPM + node dans le README ?

2022-01-07 15:29 UTC, P3rceval commented on tool.sh
> +  run_integration 2> /dev/null
Est-ce qu'on enlèverai pas la redirection de la sortie pour l'histoire de l'exit code ?

2022-01-07 15:29 UTC, P3rceval commented on api/ilos/framework/src/tests/queue.integration.spec.ts
> +  function timeout(ms) {
Appeler directement `await new Promise((resolve) => setTimeout(resolve, ms));` ou déclarer la fonction en dehors du test ?

2022-01-07 15:44 UTC, P3rceval approved these changes

2022-01-07 15:48 UTC, merged