fix: remove duplicate city response that could lead to wrong insee
betagouv/preuve-covoiturage pull request #1620
Opened 2021-12-22 15:14 UTC by P3rceval

2021-12-22 17:21 UTC, jonathanfallon requested changes

2021-12-22 17:21 UTC, jonathanfallon commented on api/services/territory/src/providers/GeoRepositoryProvider.ts
> -
L'idée de le passer dans les values est d'utiliser la préparation de la requête et d'éviter les injections. Je pense qu'il faut le garder même si c'est moins joli dans le code.

2021-12-23 09:52 UTC, P3rceval commented on api/services/territory/src/providers/GeoRepositoryProvider.ts
> -
Ah oui les injections SQL ! Bien vu !

2021-12-23 10:19 UTC, jonathanfallon approved these changes

2021-12-23 10:19 UTC, merged