fix: create relations between territory and insees
betagouv/preuve-covoiturage pull request #1621
Opened 2021-12-23 16:03 UTC by P3rceval

2021-12-23 16:10 UTC, P3rceval commented on api/services/territory/src/providers/TerritoryRepositoryProvider.ts
> -    if (data.insee !== undefined && data.insee.length > 0) {
Les insees dans le formulaire de création sont forcément tous dans territory_code. Donc à ne surtout pas recréer

2022-01-05 08:46 UTC, nmrgt requested changes

2022-01-05 08:46 UTC, nmrgt commented on api/services/territory/src/providers/TerritoryRepositoryProvider.ts
> +      this.createRelations(resultData._id, data.children);
il manque un await je pense, non ?

2022-01-05 08:46 UTC, nmrgt commented on api/services/territory/src/providers/TerritoryRepositoryProvider.ts
> +    const insertQuery = `INSERT INTO ${this.relationTable}(parent_territory_id,child_territory_id) VALUES${values}`;
Pour éviter les injections sql tu peux utiliser `INSERT INTO (f1, f2) SELECT * FROM UNNEST($1::int[], $2::int[])`

2022-01-10 08:44 UTC, nmrgt approved these changes

2022-01-11 14:21 UTC, merged