Feat/v3 spec
betagouv/preuve-covoiturage pull request #1663
Opened 2022-02-16 13:19 UTC by nmrgt

2022-09-06 12:35 UTC, nmrgt commented on api/doc/v2.yaml
>                    - status
```suggestion
                  - status
                  - message
```

2022-09-19 15:42 UTC, jonathanfallon commented on api/doc/v2.yaml
>                    - status
@nmrgt On ne pourrait pas faire la spec de la V3 dans un nouveau fichier (`v3.yaml` au hasard...) pour garder un historique de la V2 (sans aller rechercher dans le commit) ?

2022-10-11 14:43 UTC, nmrgt commented on api/doc/v2.yaml
>                    - status
oui mais j'ai gardé le nom pour pouvoir faire un diff :D

2022-10-21 09:22 UTC, nmrgt commented
Le cas des données de paiements : 
- le revenue du conducteur est égal à ce que le conducteur a effectivement perçu ;
- la contribution passager est égal à ce que le passager a effectivement payé en incluant les paiements via du FMD prépayé ou autres titres de mobilité ;
- le tableaux d'incitations doit être rempli s'il y a des incitations connues par l'opérateur ;
- le tableaux de paiements doit être rempli s'il y a des paiements via du FMD prépayé ou autres titres de mobilité ;
- la somme de contribution passager + incitations doit être égal au revenue du conducteur ;
- la somme des paiements ne peut pas être supérieure à la contribution passager ;
- l'éventuelle commission prise par l'opérateur est exclue de ces données.

Concernant les conventions avec contreparties distinctes de l’incitation (ex : je paie 10cts/km et en échange tu assures la gratuité) : il faudrait ajouter un tableau "contrepartie" pour assurer la validité de ces définitions.

2023-04-09 09:26 UTC, jonathanfallon commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit fa170f832f03d05ed79c0136fd18fa3ee0e179a6. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=1663,feat/v3_spec)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`lerna run build`](https://cloud.nx.app/runs/aEIUDRSFJ8)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-04-12 07:07 UTC, nmrgt commented
@jonathanfallon @P3rceval pouvez-vous faire la review de la PR pour qu'on puisse communiquer la spec aux opérateurs ?

2023-04-13 13:10 UTC, jonathanfallon submitted a review, later dismissed

2023-04-14 06:59 UTC, P3rceval requested changes

2023-04-14 06:59 UTC, P3rceval commented on api/doc/v3.yaml
> +        Lors de l'envoi d'un trajet, un code 201 et un payload avec le `operator_journey_id` et la date de création vous sont renvoyés. Le trajet est alors enregistré dans notre base. Le processus de
```suggestion
        Lors de l'envoi d'un trajet, un code 201 et un payload avec le `operator_journey_id` et la date de création vous sont renvoyés. Le trajet est alors enregistré dans notre base. Le processus de validation par lequel vont passer les données est complexe, asynchrone et dépend de différents services ayant de temps de réponse variables. De plus, les données d'affichage de la liste détaillée de l'interface d'administration n'est rafraîchie que toutes les 24h.
```

2023-04-14 06:59 UTC, P3rceval commented on api/doc/v3.yaml
> +        S'il détecte un comportement inhabituel ou une fraude avérée, un opérateur doit communiquer auprès du Service l'invalidation du trajet concerné dès lors qu'il est déjà inscrit dans le registr
```suggestion
        S'il détecte un comportement inhabituel ou une fraude avérée, un opérateur doit communiquer auprès du service l'invalidation du trajet concerné dès lors qu'il est déjà inscrit dans le registre. Cette invalidation doit avoir lieu dès que l'opérateur a connaissance de cette irrégularité.
```

2023-04-14 06:59 UTC, P3rceval commented on api/doc/v3.yaml
> +        S'il détecte un comportement inhabituel ou une fraude avérée, un opérateur doit communiquer auprès du Service l'invalidation du trajet concerné dès lors qu'il est déjà inscrit dans le registr
Est-ce qu'on rajouterai pas un champ texte optionnel sur le motif ? Ça permettrai d'avoir peut-être des premiers inputs concernant de la fraude ?

2023-04-14 07:39 UTC, jonathanfallon commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit 19d9e46c38c738a6a638f654cccbef5afb86572c. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=1663,feat/v3_spec)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`lerna run build`](https://cloud.nx.app/runs/5OrnUJjPUC)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-04-14 09:46 UTC, P3rceval approved these changes

2023-04-14 09:47 UTC, merged