configure dashboard display in public stats
betagouv/preuve-covoiturage pull request #1695
Opened 2022-03-22 13:29 UTC by jonathanfallon

2022-03-22 14:03 UTC, P3rceval requested changes

2022-03-22 14:03 UTC, P3rceval commented on dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.html
> +    src="https://stats.covoiturage.beta.gouv.fr/embed/dashboard/3bec1692-1456-41c2-95a9-6606af329df9#bordered=false&titled=false"
Il faut aussi fix le lien opendata cf [cette PR](https://github.com/betagouv/preuve-covoiturage/pull/1696/files).
J'ai repris tes changements dans ma PR

2022-03-23 13:40 UTC, jonathanfallon commented on dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.html
> +    src="https://stats.covoiturage.beta.gouv.fr/embed/dashboard/3bec1692-1456-41c2-95a9-6606af329df9#bordered=false&titled=false"
On ferme celle-ci ?

2022-03-28 12:35 UTC, closed without merging

2022-03-28 12:35 UTC, P3rceval commented
Duplicate