Feat: trip service migration
betagouv/preuve-covoiturage pull request #1750
Opened 2022-06-13 15:23 UTC by nmrgt

- mise a jour du middleware "scopeByGroup"
- mise à jour des provider sql
- mise à jour des mécanisme d'exclusion de territoire

2022-06-15 15:22 UTC, jonathanfallon requested changes
j'ai fait quelques commentaires. On peut en discuter à un moment demain

2022-06-15 15:22 UTC, jonathanfallon commented on shared/trip/common/interfaces/TerritoryTripsInterface.ts
> +  end_geo_code?: number;
c'est pas un `string` ici ?

2022-06-15 15:22 UTC, jonathanfallon commented on api/services/trip/src/middleware/ScopeToGroupMiddleware.integration.spec.ts
> +        territory_id: 1,
On a encore des `territory_id` qqpart ?

2022-06-15 15:22 UTC, jonathanfallon commented on api/services/territory/src/actions/geo/ListGeoAction.ts
> +    copyFromContextMiddleware('call.user.authorizedZoneCodes.com', 'where.insee'),
Pourrait-on normaliser le naming ?
J'ai peur que l'on se trompe si on doit convertir com <> insee et inversement.
S'il faut faire un refacto du frontend pour tout nommer en `com`, faisons le.

2022-06-15 15:22 UTC, jonathanfallon commented on api/services/trip/src/cron/TripCacheWarmCron.ts
> +      const authorizedZoneCodes = await this.kernel.call<GetAuthorizedCodesParamsInterface,GetAuthorizedCodesResultInterface>(
Je me pose la question de la pertinence de cette routine. Je n'ai pas l'impression que ce soit super efficace et on devrait supprimer les stats à terme.

2022-06-15 15:29 UTC, nmrgt commented on shared/trip/common/interfaces/TerritoryTripsInterface.ts
> +  end_geo_code?: number;
```suggestion
  end_geo_code?: string;
```

2022-06-15 15:29 UTC, nmrgt commented on api/services/trip/src/middleware/ScopeToGroupMiddleware.integration.spec.ts
> +        territory_id: 1,
oui pour le rattachement à un territoire comme groupe d'utilisateur

2022-06-15 15:30 UTC, nmrgt commented on api/services/territory/src/actions/geo/ListGeoAction.ts
> +    copyFromContextMiddleware('call.user.authorizedZoneCodes.com', 'where.insee'),
oui on peut et ce serait bien effectivement
tu le fais ?

2022-06-15 15:32 UTC, nmrgt commented on api/services/trip/src/cron/TripCacheWarmCron.ts
> +      const authorizedZoneCodes = await this.kernel.call<GetAuthorizedCodesParamsInterface,GetAuthorizedCodesResultInterface>(
cette pr n'intervient pas directement sur ce champs, elle fait juste le passage vers le nouveau référentiel géographique. on peut questionner cette routine mais peut être dans une autre pr :)

2022-06-15 15:58 UTC, jonathanfallon commented on api/services/territory/src/actions/geo/ListGeoAction.ts
> +    copyFromContextMiddleware('call.user.authorizedZoneCodes.com', 'where.insee'),
il faut que j'arrive à faire tourner le nouveau code avant ...

2022-06-20 07:39 UTC, nmrgt commented on api/services/territory/src/actions/geo/ListGeoAction.ts
> +    copyFromContextMiddleware('call.user.authorizedZoneCodes.com', 'where.insee'),
hors scope de la PR

2022-06-21 09:37 UTC, P3rceval commented
Tests OK en local suite aux corrections : 

- Export / Stats ETQ operateur avec et sans filtre sur une commune
- Export / Stats ETQ territoire avec et sans filtre sur une commune. (Les requêtes sans filtre défini appliquent bien par défaut la liste de communes paramétrées pour le territoire )

2022-06-21 09:54 UTC, P3rceval commented
PR séparée pour pouvoir exporter sur AOM/EPIC ect ...

2022-06-21 10:09 UTC, jonathanfallon approved these changes

2022-06-21 10:37 UTC, merged