feat: generate phone file tool
betagouv/preuve-covoiturage pull request #1903
Opened 2022-11-14 11:44 UTC by nmrgt

Outil pour générer les fichiers de correspondance entre des uuids et des numéros de téléphone

2022-11-14 16:20 UTC, jonathanfallon commented
![image](https://user-images.githubusercontent.com/1656255/201711416-e0cd5938-8c78-4953-9a23-93dfb81a027b.png)
Le `shuf` pique un peu sur l'utilisation de la RAM...

2022-11-14 17:37 UTC, jonathanfallon commented
Il y a une lib plus performante que les UUID (x1.5 à x2 sur les perfs de génération) qui est https://www.npmjs.com/package/nanoid
Sur ma machine, c'est + de 2h de génération des fichiers...

2022-11-14 22:21 UTC, jonathanfallon commented
Avec `nanoid`: 36 minutes de génération des fichiers

2022-11-23 13:57 UTC, ccyrille requested changes
Merci pour cette proposition d'implémentation.Il me semble qu'il y a un trou dans la sécurité des données (+ un petit souci dans le `$REGISTRY_FINAL_FILE`). À dispo pour itérer.

2022-11-23 13:57 UTC, ccyrille commented on tools/phone.sh
> +export REGISTRY_FINAL_FILE=$WORKING_DIRECTORY/data_registry_final.csv
```suggestion
export REGISTRY_FINAL_FILE=$REGISTRY_DIRECTORY/data_registry_final.csv
```

2022-11-23 13:57 UTC, ccyrille commented on tools/phone.sh
> +    split -l 1000000 --filter='shuf' $REGISTRY_FILE | pv -ptl -s$SIZE | $GZIP_CMD > $REGISTRY_DIRECTORY/$REGISTRY_FINAL_FILE.gz && rm $REGISTRY_FILE
```suggestion
    split -l 1000000 --filter='shuf' $REGISTRY_FILE | pv -ptl -s$SIZE | $GZIP_CMD > $REGISTRY_FINAL_FILE.gz && rm $REGISTRY_FILE
```

2022-11-23 13:57 UTC, ccyrille commented on tools/phone.sh
> +  $GZIP_CMD $OPERATOR_1_FILE && mv $OPERATOR_1_FILE.gz $OPERATOR_1_DIRECTORY
Les valeurs de `$OPERATOR_X_DIRECTORY` et `$REGISTRY_DIRECTORY` sont-elles destinées à rester `$(pwd)` ? 

Si c'est le cas, cela veut dire que les fichiers transitent pas le système de fichier principal. Et si l'un des fichiers opérateurs ou le fichier RPC transitent par le système de fichier principal avant d'être placés sur les clés USB, l'utilisation d'un FS temporaire n'apporte à priori rien en termes de sécurité des données.

2022-11-23 14:09 UTC, nmrgt commented on tools/phone.sh
> +  $GZIP_CMD $OPERATOR_1_FILE && mv $OPERATOR_1_FILE.gz $OPERATOR_1_DIRECTORY
Merci pour tes retour @ccyrille. Non je te rassure, l'idée est de mettre les chemins vers les différentes clés usb sur ces valeurs.

2023-02-08 08:43 UTC, P3rceval approved these changes

2023-02-09 09:33 UTC, merged

2023-02-09 09:34 UTC, jonathanfallon commented
Je merge la PR vu qu'elle est validée et qu'elle n'impacte que des outils périphériques au code de l'appli.