[fix] résolution des INSEE des pays voisins
betagouv/preuve-covoiturage pull request #1935
Opened 2022-12-16 15:52 UTC by jonathanfallon

Suite à l'évolution en 1.2.1 du paquet geo, il est possible d'utiliser `geo.get_closest_country` à la place de `geo.get_latest_by_point` pour résoudre le code INSEE d'un point géographique.

Les contours des pays limitrophes étant volontairement imprécis pour des raisons de performances, il est nécessaire d'utiliser cette fonction de résolution.

2022-12-19 12:10 UTC, nmrgt requested changes

2022-12-20 09:55 UTC, jonathanfallon commented on api/providers/geo/src/providers/LocalGeoProvider.ts
> +  protected fn = 'geo.get_closest_country';
C'était ma première approche et j'ai testé comme ça au début mais ça fonctionne mieux en utilisant directement cette fonction.

2022-12-21 15:19 UTC, jonathanfallon commented on api/providers/geo/src/providers/LocalGeoProvider.ts
> +  protected fn = 'geo.get_closest_country';
je suis passé sur un `UNION` des deux fonctions avec une exclusion de tous les pays dans la première pour être sûr d'avoir une commune et non le pays FRANCE.

2022-12-22 09:51 UTC, P3rceval commented on api/proxy/load/acquisition_create.js
> +          lat: 49.45218,
Pourquoi avoir modifier les coordonnées ici ?

2022-12-22 09:51 UTC, P3rceval submitted a review, later dismissed

2023-01-03 14:52 UTC, jonathanfallon commented on api/proxy/load/acquisition_create.js
> +          lat: 49.45218,
Pour avoir un point au Luxembourg qui n'est pas couvert par une maille géographique Française ou Luxembourgeoise (cas d'usage qui plante)

2023-01-04 09:11 UTC, merged