Add override_until param to campaign:apply
betagouv/preuve-covoiturage pull request #2032
Opened 2023-02-20 10:02 UTC by jonathanfallon

Ajout du paramètre `override_until` pour pouvoir faire des `campaign:apply` progressivement.

Ajout du fichier `apply.schema` pour valider les inputs et les caster dans le bon format.

2023-02-20 10:03 UTC, jonathanfallon commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit 40c3bf813e148b2766bd578f0468bf1e555fbacf. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=2032,feat/campaign-apply-end-date)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`lerna run build`](https://cloud.nx.app/runs/Acg79ze1LC)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-04-05 08:08 UTC, nmrgt requested changes

2023-04-05 08:08 UTC, nmrgt commented on api/services/policy/src/actions/ApplyAction.ts
> +  middlewares: [...internalOnlyMiddlewares(handlerConfig.service), ['validate', alias]],
Bon je met le commentaire ici mais c'est pas forcément là le soucis. Dans ton implementation, tu ajoutes en obligatoire le "policy_id" sauf que le comportement actuel est d'appeler l'action via un cron sans paramètre (voir methode "init") pour faire l'ensemble des campagnes et dans le cas ou il n'y a pas de policy_id faire l'ensemble des politiques actives. Sauf si j'ai raté quelque chose, l'action ne va rien faire du tout et il faudra faire les campagnes manuellement chaque semaine ?

2023-04-05 08:08 UTC, nmrgt commented on api/services/policy/src/actions/FinalizeAction.ts
> +      to: params.to ?? today(tz),
actuellement, on process "de base" tous les trajets (from = null) jusqu'à il y a 7 jours (5 jours pour les opérateurs et 2 jours de "marge) et non tous les trajets de la semaine passé. Je pense qu'il y a un soucis avec ces défauts puisqu'on peut recevoir des trajets jusqu'à 5 jours après. Si tu veux être sur une semaine (?), il faut faire -14 jours, -7 jours en défaut.

2023-04-11 08:22 UTC, jonathanfallon commented on api/services/policy/src/actions/ApplyAction.ts
> +  middlewares: [...internalOnlyMiddlewares(handlerConfig.service), ['validate', alias]],
L'action est appelée par la commande `campaign:process` qui s'occupe de normaliser les paramètres et d'éxecuter l'action en sync ou async.
On a vu qu'avec la migration chez Scaleway, la gestion des CRON doit être modifiée donc ça implique de nouvelles modifs...

2023-04-11 08:29 UTC, jonathanfallon commented on api/services/policy/src/actions/ApplyAction.ts
> +      to: params.to ?? today(tz),
Il y a un petit soucis de logique ici, je corrige ça.

2023-04-11 09:05 UTC, jonathanfallon commented on api/services/policy/src/actions/FinalizeAction.ts
> +      to: params.to ?? today(tz),
Vu plus haut. La logique est corrigée pour appliquer de -7 à 0 jours et finaliser de -14 à -5 jours

2023-04-11 09:05 UTC, jonathanfallon commented
Utilisation des `cron.json` pour cette PR en attendant une PR plus générale de migration des CRON sur le système de Scaleway

2023-04-12 07:02 UTC, merged