feat: Colonne des trajets incités
betagouv/preuve-covoiturage pull request #2033
Opened 2023-02-20 23:29 UTC by jonathanfallon

Ajout de la colonne des trajets incités dans l'onglet "Tranches" des APDF.
Améliorations du layout du XLSX.

2023-02-20 23:31 UTC, jonathanfallon commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit 6138c69587215803b24a07fc741c75708fcd4813. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=2033,feat/apdf-layout-improvements)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`lerna run build`](https://cloud.nx.app/runs/WvBKlznnrG)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-02-20 23:43 UTC, jonathanfallon commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit bf1564007ab1570abeea613b93ae5ca0f3dc869c. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=2033,feat/apdf-layout-improvements)

---

| 🟥 Failed Commands | 
| --- | 
| [`lerna run test:integration`](https://cloud.nx.app/runs/3qJCUEOyIr) | 

<details>
<summary>✅ Successfully ran 2 targets </summary>

- [`lerna run build`](https://cloud.nx.app/runs/cz4t4TVg8f)
- [`lerna run test:unit`](https://cloud.nx.app/runs/Ru7VOXaLnh)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-02-21 08:31 UTC, P3rceval requested changes

2023-02-21 08:31 UTC, P3rceval commented on api/services/apdf/src/providers/excel/BuildExcel.ts
> +    private TripsWsWriter: TripsWorksheetWriter,
```suggestion
    private tripsWsWriter: TripsWorksheetWriter,
```

2023-02-21 08:31 UTC, P3rceval commented on api/services/apdf/src/providers/excel/BuildExcel.ts
> +      await this.TripsWsWriter.call(tripCursor, wkw);
```suggestion
      await this.tripsWsWriter.call(tripCursor, wkw);
```

2023-03-02 11:08 UTC, P3rceval approved these changes

2023-03-02 11:08 UTC, merged