Feat/policy update
betagouv/preuve-covoiturage pull request #2112
Opened 2023-04-20 15:09 UTC by P3rceval

```
INSERT INTO policy.policies(
	_id,      created_at, updated_at, deleted_at, territory_id, start_date, end_date, name, description, unit, status, handler, incentive_sum, max_amount)
	VALUES
	(DEFAULT, DEFAULT,    DEFAULT,    NULL, 36330, '2023-04-01 00:00:00+00', '2023-12-31 00:00:00+00', 'PBA_2023_04', NULL, 'euro', 'active', 'pays_basque_2023', 0, 5000000);

INSERT INTO TERRITORY.TERRITORY_GROUP_SELECTOR VALUES (36330, 'com', 40209);
INSERT INTO TERRITORY.TERRITORY_GROUP_SELECTOR VALUES (36330, 'com', 40273);
```

2023-04-20 15:11 UTC, jonathanfallon commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit dfc9e243a344f4c19eea1407c274b64cb2246d7b. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=2112,feat/policy-update)

---


<details>
<summary>✅ Successfully ran 2 targets </summary>

- [`lerna run test:unit`](https://cloud.nx.app/runs/MQ17f7SXE0)
- [`lerna run build`](https://cloud.nx.app/runs/XELPPGjQLX)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-04-28 12:11 UTC, nmrgt requested changes

2023-04-28 12:11 UTC, nmrgt commented on api/services/policy/src/engine/policies/PaysBasque.ts
> +    onDistanceRangeOrThrow(ctx, { min: 5_000 });
Ne manque-t-il pas la borne haute?

2023-04-28 12:11 UTC, nmrgt commented on api/services/policy/src/engine/policies/PaysBasque.ts
> +
Sur les passagers "gratuits" ça n'impacte donc pas le calcul ?

2023-04-28 12:11 UTC, nmrgt commented on api/services/policy/src/engine/policies/Smt2023.ts
> +    return new Date() >= new Date('2023-04-15');
Timezone ?

2023-04-28 15:17 UTC, P3rceval commented on api/services/policy/src/engine/policies/PaysBasque.ts
> +    onDistanceRangeOrThrow(ctx, { min: 5_000 });
Y'a pas de limite d'indiquer dans la fiche descriptif. Si tu fais 150km dans le pays basque, t'es incité à hauteur de 3€

2023-04-28 15:17 UTC, P3rceval commented on api/services/policy/src/engine/policies/PaysBasque.ts
> +
Dans la fiche descriptive, c'est indiqué en tant que contrepartie opérateur, ça ne doit donc pas être calculer par le RPC.

2023-04-28 15:17 UTC, P3rceval commented on api/services/policy/src/engine/policies/Smt2023.ts
> +    return new Date() >= new Date('2023-04-15');
yes c'est corrigé !

2023-05-02 08:23 UTC, nmrgt commented on api/services/policy/src/engine/policies/PaysBasque.ts
> +    onDistanceRangeOrThrow(ctx, { min: 5_000 });
Ligne 12 sur PaysBasque.html.ts dis : "Au-delà de 30 km : pas d’incitation financière". C'est juste un problème de rédaction dans la description peut-être mais j'avais compris qu'au dessus de ce seuil il n'y avait pas d'incitation.

2023-05-02 08:23 UTC, nmrgt commented on api/services/policy/src/engine/policies/PaysBasque.ts
> +
top

2023-05-02 11:56 UTC, P3rceval commented on api/services/policy/src/engine/policies/PaysBasque.ts
> +    onDistanceRangeOrThrow(ctx, { min: 5_000 });
A oui problème dans la description. Je supprime cette ligne

2023-05-02 12:12 UTC, nmrgt approved these changes

2023-05-02 12:12 UTC, merged