Obs/add indicator endpoint
betagouv/preuve-covoiturage pull request #2166
Opened 2023-06-08 14:21 UTC by Datayama38

2023-06-08 14:29 UTC, jonathanfallon commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit 2a52dd4a431c52a09e43aa44c6d62892b4db831b. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=2166,obs/add_indicator_endpoint)

---


<details>
<summary>✅ Successfully ran 3 targets </summary>

- [`lerna run test:integration`](https://cloud.nx.app/runs/f2hjqbZkpY)
- [`lerna run build`](https://cloud.nx.app/runs/0w6maFWQ3V)
- [`lerna run test:unit`](https://cloud.nx.app/runs/yNmbHUnumS)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-06-08 19:59 UTC, jonathanfallon reviewed
J'ai typé les contrats et les schemas du dossier `shared` pour clarifier les choses et éviter les duplications.
Si les propriétés `code` dans les schemas sont des codes INSEE, il est préférable d'utiliser le code ci-dessous pour rester DRY.

```json
code: { "macro": "insee" }
```

2023-06-08 20:22 UTC, jonathanfallon commented on api/proxy/src/HttpTransport.ts
> +      '/observatory/monthly_keyfigures',
Dans ce cas il faudrait aussi changer les autres.

2023-06-08 20:44 UTC, Datayama38 commented on api/proxy/src/HttpTransport.ts
> +      '/observatory/monthly_keyfigures',
ok je vais les changer

2023-06-08 20:49 UTC, Datayama38 commented
Pour le champ code, je l'utilise pour tous les types de codes (Insee pour les communes, régions, département et  pays mais siret pour les epci et aom. Je sais pas si ça rentre dans la définition de champ que tu mentionnes.

2023-06-09 07:47 UTC, jonathanfallon commented
Dans ce cas et si on veut faire les choses bien, on peut utiliser ça :

```ts
code: {
  oneOf: [
    { macro: 'insee' },
    { macro: 'siret' }
  ]
}
```

2023-06-12 08:16 UTC, nmrgt requested changes

2023-07-13 15:02 UTC, jonathanfallon submitted a review, later dismissed

2023-07-13 15:03 UTC, jonathanfallon commented
@Datayama38 les `macro` dans les schemas fonctionnent ?

2023-07-18 12:16 UTC, jonathanfallon commented
Les migrations `007`, `008` et `009` ne sont pas utilisées.
Il faut créer un nouveau fichier `.js` pour appeler les migrations `sql`.

2023-07-18 12:58 UTC, jonathanfallon commented
Imports des custom string formats corrigés

2023-08-31 08:26 UTC, merged

2023-09-04 08:44 UTC, P3rceval commented
:tada: This PR is included in version 3.9.5 :tada:

The release is available on [GitHub release](https://github.com/betagouv/preuve-covoiturage/releases/tag/v3.9.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: