Ajout notebook fraude triangulaire
betagouv/preuve-covoiturage pull request #2195
Opened 2023-07-06 08:29 UTC by panayo

2023-07-06 08:31 UTC, jonathanfallon commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit 5f8dee58de82c03e619dcd22f9e500656b023b51. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=2195,feat/fraude_triangulaire)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`lerna run build`](https://cloud.nx.app/runs/eWp9bQNICv)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-07-10 12:46 UTC, P3rceval requested changes

2023-07-13 07:23 UTC, panayo commented on notebooks/scripts/production/20230701000000_create_potential_triangular_patterns.sql
@P3rceval oui c'est une erreur de sauvegarde je vais re pousser le bon fichier.

2023-07-13 08:35 UTC, panayo commented on notebooks/scripts/production/users-patterns-insights.ipynb
> +    "   LEFT JOIN policy.incentives pi on pi.carpool_id = cc._id and pi.policy_id = '{policy_id}'\n",
Je ne vois pas comment récupérer les incentives, si tu vois une meilleure approche n'hésite pas.

2023-07-13 08:36 UTC, panayo commented on notebooks/scripts/production/users-patterns-insights.ipynb
C'est fait il y a deux notebook le manuel avec `start_date` `end_date` et l'autre qui utilise `delay` et `frame`.

2023-07-19 07:48 UTC, P3rceval commented on notebooks/scripts/production/users-patterns-insights.ipynb
> +    "   LEFT JOIN policy.incentives pi on pi.carpool_id = cc._id and pi.policy_id = '{policy_id}'\n",
` LEFT JOIN policy.incentives pi on pi.carpool_id = cc._id`

2023-07-19 07:48 UTC, P3rceval commented on notebooks/scripts/production/users-patterns-insights.ipynb
> +    "   LEFT JOIN policy.incentives pi on pi.carpool_id = cc._id and pi.policy_id = '{policy_id}'\n",
On enlève juste le critère `policy_id` sur la jointure :)

2023-07-20 07:27 UTC, panayo commented on notebooks/scripts/production/users-patterns-insights.ipynb
> +    "   LEFT JOIN policy.incentives pi on pi.carpool_id = cc._id and pi.policy_id = '{policy_id}'\n",
Oui c'était simple :)

2023-07-20 08:06 UTC, merged

2023-07-20 08:07 UTC, P3rceval commented
:tada: This PR is included in version 3.5.8 :tada:

The release is available on [GitHub release](https://github.com/betagouv/preuve-covoiturage/releases/tag/v3.5.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: