fix(export): Promisify cursor.read
betagouv/preuve-covoiturage pull request #2271
Opened 2023-09-14 16:26 UTC by jonathanfallon

Promisify de `pg-cursor` `read` function.
Bump versions

2023-09-14 16:32 UTC, jonathanfallon commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit 181c0ae5d411ffc6a69e5ae196122aa3d48ded46. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=2271,fix/trip-exports)

---

| 🟥 Failed Commands |
| --- |
| [`lerna run build`](https://cloud.nx.app/runs/TCysC7i2BT) | 


---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-09-15 07:24 UTC, nmrgt requested changes

2023-09-15 07:24 UTC, nmrgt commented on api/proxy/src/config/proxy.ts
> +export const showcase = env('APP_SHOWCASE_URL', 'https://localhost:1313');
il faut utiliser env.or_fail

2023-09-15 07:24 UTC, nmrgt commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +
À priori la dernière version utilise des promises : https://node-postgres.com/apis/cursor#cursorreadrowcount-number--promisepgresult

2023-09-15 07:24 UTC, nmrgt commented on api/ilos/connection-postgres/package.json
> +    "pg-cursor": "^2.10.3"
Pour info, ce changement n'a pas d'impact sur les versions installées (c'était déjà les dernières à jour)

2023-09-15 07:24 UTC, nmrgt commented on api/services/trip/src/actions/file/BuildFile.ts
> +      await cursor.release();
cursor.close() ?

https://node-postgres.com/apis/cursor#close

2023-09-15 07:31 UTC, nmrgt commented on api/services/trip/src/actions/file/BuildFile.ts
> +      await cursor.release();
Vu plus bas c'est effectivement release qui appelle close.

2023-09-15 10:05 UTC, jonathanfallon commented on api/services/trip/src/providers/TripRepositoryProvider.ts
> +
C'est exactement le code qui ne fonctionnait pas... j'ai mis les paquets à jour mais ça n'a pas suffit. Je préfère rester conservateur sur qqch qui marche.

2023-09-15 10:06 UTC, jonathanfallon commented on api/ilos/connection-postgres/package.json
> +    "pg-cursor": "^2.10.3"
Je suis reparti de la branche `main` donc je dirais que non ou alors il y a un soucis de workflow git

2023-09-15 10:08 UTC, jonathanfallon commented on api/services/trip/src/actions/file/BuildFile.ts
> +      await cursor.release();
Yes. Je mets ça dans le catch aussi pour être sûr

2023-09-18 08:17 UTC, P3rceval approved these changes

2023-09-19 07:02 UTC, merged

2023-09-19 07:03 UTC, P3rceval commented
:tada: This PR is included in version 3.12.1 :tada:

The release is available on [GitHub release](https://github.com/betagouv/preuve-covoiturage/releases/tag/v3.12.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: